language: php

php:
  - 7.2
  - 7.3
  - 7.4
  - 8.0
  - nightly

jobs:
  # PHP's argument names are being changed until 8.0.0 stable is released in November,
  # leading to build failures unrelated to Phan itself.
  allow_failures:
  - php: nightly

# NOTE: Travis starts up 5 test suites at a time.
# So, it's faster to run all of the tests at once per supported PHP version.
dist: xenial
sudo: false

# We invoke php multiple times via CLI in several tests, so enable the opcache file cache.
before_install:
  - composer validate

# --classmap-authoritative shouldn't affect Phan's behavior, but is faster.
# Use it for Travis and published Phars.
install:
  - composer --prefer-dist --classmap-authoritative install

script:
  - vendor/bin/phpunit
  - vendor/bin/phan
